#!/usr/bin/env bash
# install.sh - One-click deployment of DeepSeek Harness (dsh) with LAN access.
#
# What it does:
#   1. Ensure Node.js (>= 22) is available (installs nvm + LTS if missing)
#   2. Install @deepseek-ai/dsh globally
#   3. Generate env.sh pinning this machine's paths
#   4. Optionally register desktop auto-start and a systemd --user service
#   5. Start the service and print access URLs
#
# Usage:
#   bash install.sh                 # interactive defaults
#   bash install.sh --no-autostart  # skip login auto-start registration
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=============================================="
echo " DeepSeek Harness 局域网部署安装器"
echo "=============================================="

# ---------- 1. Node.js ----------
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
if ! command -v node >/dev/null 2>&1; then
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
fi

if command -v node >/dev/null 2>&1; then
  NODE_BIN_DIR="$(dirname "$(readlink -f "$(command -v node)")")"
  echo "[1/4] 检测到 Node.js $(node -v)"
else
  echo "[1/4] 未检测到 Node.js，尝试通过 nvm 安装 LTS ..."
  if [ ! -s "$NVM_DIR/nvm.sh" ]; then
    read -r -p "将下载并安装 nvm + Node.js LTS，继续? [Y/n] " yn
    case "$yn" in n*|N*) echo "已取消。请自行安装 Node.js >= 22 后重试"; exit 1;; esac
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
  fi
  . "$NVM_DIR/nvm.sh"
  nvm install --lts
  NODE_BIN_DIR="$(dirname "$(readlink -f "$(command -v node)")")"
fi

# ---------- 2. dsh ----------
echo "[2/4] 安装 @deepseek-ai/dsh（全局）..."
npm install -g \
  --allow-scripts=@deepseek-ai/dsh-subprocess-local,koffi,node-pty,@google/genai,protobufjs \
  @deepseek-ai/dsh || { echo "npm 安装失败"; exit 1; }

# ---------- 3. env.sh ----------
echo "[3/4] 写入本机配置 env.sh"
cat > "$SCRIPT_DIR/env.sh" <<EOF
# generated by install.sh on $(date '+%F %T')
DEPLOY_DIR="$SCRIPT_DIR"
NODE_BIN_DIR="$NODE_BIN_DIR"
EOF

chmod +x "$SCRIPT_DIR"/*.sh "$SCRIPT_DIR/proxy.js" 2>/dev/null || true

# ---------- optional integrations ----------
AUTOSTART=1
[ "${1:-}" = "--no-autostart" ] && AUTOSTART=0

if [ "$AUTOSTART" -eq 1 ] && [ -d "$HOME/.config/autostart" ]; then
  mkdir -p "$HOME/.config/autostart"
  cat > "$HOME/.config/autostart/dsh-harness.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=DeepSeek Harness
Comment=Start DeepSeek Harness (dsh) web UI + LAN proxy on login
Exec=$SCRIPT_DIR/start.sh
Terminal=false
Hidden=false
X-GNOME-Autostart-enabled=true
EOF
  echo "  - 已注册桌面自启动 (~/.config/autostart/dsh-harness.desktop)"
fi

mkdir -p "$HOME/.config/systemd/user"
cat > "$HOME/.config/systemd/user/deepseek-harness.service" <<EOF
[Unit]
Description=DeepSeek Harness (dsh) web UI + LAN proxy
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=PATH=$NODE_BIN_DIR:/usr/bin:/bin
WorkingDirectory=$SCRIPT_DIR
ExecStart=$SCRIPT_DIR/run.sh
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
echo "  - 已写入 systemd 用户服务 (~/.config/systemd/user/deepseek-harness.service)"
echo "    启用: systemctl --user daemon-reload && systemctl --user enable --now deepseek-harness.service"

# ---------- 4. start ----------
echo "[4/4] 启动服务..."
setsid bash "$SCRIPT_DIR/start.sh" > "$SCRIPT_DIR/start.out" 2>&1 < /dev/null &
disown
sleep 10
cat "$SCRIPT_DIR/start.out"

LAN_IP="$(ip -4 route get 1 2>/dev/null | awk '{print $7; exit}')"
echo
echo "管理台: $SCRIPT_DIR/dsh.sh   (status|start|stop|restart|log|upgrade)"
echo
echo "⚠️ 安全提示: 服务已对局域网开放且解锁了设置/凭据功能(见 patch-lan.sh)，"
echo "   请仅在可信网络使用；如启用 ufw 需放行: sudo ufw allow ${PROXY_PORT:-3080}/tcp"
